### ISSUE TITLE
Incorrect calculation of `rewards_sigma` for SAU-UCB?

### ISSUE THREAD

**Issue by vbernardes** [IBM/sau-explore#3]
Hello folks,

In the paper, the SAU-UCB exploration equation is given as (in Algorithm 4):

![Captura de Tela 2024-01-11 às 17 10 46](https://github.com/IBM/sau-explore/assets/30302795/ba1bdc09-2e37-40d3-b9ae-553beca94ffb)

However, the line of code that computes the second part of that sum, for exploration, is implemented as:
https://github.com/IBM/sau-explore/blob/e85c7bac3a20c03b02623927791d6817f2ed296e/sau_agents.py#L214

Shouldn't the division by `self.n_a` be inside the square root as well? i.e.:
```python
re["rewards_sigma"] = (self.sau2 * self.n_a.sum().log() / self.n_a).sqrt()
```

**Comment by matrig** [comment]
Hello @vbernardes, thanks for your interest in our work!

The code is actually correct and consistent with the paper, but it is indeed a bit confusing. In fact, the term `self.sau2` in the code corresponds to $S^2_a$ in the paper, not to $\tau^2_a$. Because $\tau^2_a=S^2_a/n_a$ things should be consistent.

Feel free to reach out by email if you want to discuss anything else. In particular, we'd be interested to know what applications you're looking into for SAU-UCB, if you care to chat about that.

**Comment by matrig** [comment]
Closing this issue, as it should be resolved
